// ADDITIVE CATEGORIES
export const ADDITIVE_CATEGORIES = {
  sweeteners: new Set([
    "en:e950",
    "en:e951",
    "en:e952",
    "en:e954",
    "en:e955",
    "en:e957",
    "en:e959",
    "en:e960",
    "en:e961",
    "en:e962",
    "en:e965",
    "en:e966",
    "en:e967",
    "en:e968",
    "en:e969",
    "aspartame",
    "acesulfame-k",
    "acesulfame-potassium",
    "acesulfame potassium",
    "saccharin",
    "sucralose",
    "neotame",
    "advantame",
    "cyclamate",
    "thaumatin",
    "neohesperidine",
    "maltitol",
    "sorbitol",
    "mannitol",
    "isomalt",
    "xylitol",
    "erythritol",
    "lactitol",
  ]),
  colors: new Set([
    "en:e102",
    "en:e104",
    "en:e107",
    "en:e110",
    "en:e122",
    "en:e123",
    "en:e124",
    "en:e127",
    "en:e128",
    "en:e129",
    "en:e131",
    "en:e132",
    "en:e133",
    "en:e142",
    "en:e150a",
    "en:e150b",
    "en:e150c",
    "en:e150d",
    "en:e151",
    "en:e154",
    "en:e155",
    "en:e171",
    "en:e172",
    "en:e173",
    "en:e174",
    "en:e175",
    "en:e180",
    "tartrazine",
    "sunset-yellow",
    "sunset yellow",
    "allura-red",
    "allura red",
    "brilliant-blue",
    "brilliant blue",
    "indigo-carmine",
    "indigo carmine",
    "erythrosine",
    "ponceau-4r",
    "carmoisine",
    "azorubine",
    "amaranth",
    "patent-blue-v",
    "quinoline-yellow",
    "titanium-dioxide",
    "titanium dioxide",
    "caramel",
  ]),
  preservatives: new Set([
    "en:e200",
    "en:e201",
    "en:e202",
    "en:e203",
    "en:e210",
    "en:e211",
    "en:e212",
    "en:e213",
    "en:e214",
    "en:e215",
    "en:e216",
    "en:e217",
    "en:e218",
    "en:e219",
    "en:e220",
    "en:e221",
    "en:e222",
    "en:e223",
    "en:e224",
    "en:e226",
    "en:e227",
    "en:e228",
    "en:e230",
    "en:e231",
    "en:e232",
    "en:e233",
    "en:e234",
    "en:e235",
    "en:e239",
    "en:e242",
    "en:e249",
    "en:e250",
    "en:e251",
    "en:e252",
    "sodium-benzoate",
    "sodium benzoate",
    "potassium-sorbate",
    "potassium sorbate",
    "sodium-nitrite",
    "sodium nitrite",
    "sodium-nitrate",
    "sodium nitrate",
    "sulfur-dioxide",
    "sulfur dioxide",
    "bha",
    "bht",
    "tbhq",
    "propyl-gallate",
    "propyl gallate",
    "parabens",
    "methylparaben",
    "propylparaben",
    "butylparaben",
  ]),
  flavorEnhancers: new Set([
    "en:e620",
    "en:e621",
    "en:e622",
    "en:e623",
    "en:e624",
    "en:e625",
    "en:e626",
    "en:e627",
    "en:e628",
    "en:e629",
    "en:e630",
    "en:e631",
    "en:e632",
    "en:e633",
    "en:e634",
    "en:e635",
    "en:e636",
    "en:e637",
    "en:e640",
    "en:e641",
    "monosodium-glutamate",
    "monosodium glutamate",
    "msg",
    "disodium-guanylate",
    "disodium guanylate",
    "disodium-inosinate",
    "disodium inosinate",
    "disodium-5-ribonucleotides",
    "disodium 5 ribonucleotides",
  ]),
  // DAIRY PRODUCTS
  dairy: new Set([
    "milk",
    "whole milk",
    "skim milk",
    "nonfat milk",
    "powdered milk",
    "milk powder",
    "dried milk",
    "milk solids",
    "cream",
    "heavy cream",
    "whipping cream",
    "sour cream",
    "cheese",
    "cheddar",
    "parmesan",
    "mozzarella",
    "cream cheese",
    "butter",
    "buttermilk",
    "butter oil",
    "whey",
    "whey protein",
    "whey powder",
    "casein",
    "caseinate",
    "sodium caseinate",
    "calcium caseinate",
    "lactose",
    "yogurt",
    "yogurt powder",
    "ghee",
    "condensed milk",
    "evaporated milk",
    "half and half",
    "half-and-half",
  ]),
  // TREE NUTS
  treeNuts: new Set([
    "almond",
    "almonds",
    "cashew",
    "cashews",
    "walnut",
    "walnuts",
    "pecan",
    "pecans",
    "hazelnut",
    "hazelnuts",
    "pistachio",
    "pistachios",
    "macadamia",
    "macadamia nut",
    "macadamia nuts",
    "brazil nut",
    "brazil nuts",
    "pine nut",
    "pine nuts",
    "chestnut",
    "chestnuts",
    "almond oil",
    "walnut oil",
    "hazelnut oil",
  ]),
  // PEANUTS
  peanuts: new Set([
    "peanut",
    "peanuts",
    "peanut oil",
    "peanut butter",
    "peanut flour",
    "groundnut",
    "groundnuts",
  ]),
  // GLUTEN/WHEAT
  gluten: new Set([
    "wheat",
    "wheat flour",
    "whole wheat",
    "wheat starch",
    "wheat gluten",
    "wheat protein",
    "barley",
    "barley malt",
    "malt",
    "malt extract",
    "malt syrup",
    "rye",
    "rye flour",
    "spelt",
    "spelt flour",
    "gluten",
    "vital wheat gluten",
    "wheat bran",
    "wheat germ",
    "durum",
    "semolina",
    "kamut",
    "farro",
    "triticale",
  ]),
  // SHELLFISH
  shellfish: new Set([
    "shrimp",
    "prawn",
    "prawns",
    "crab",
    "lobster",
    "crayfish",
    "crawfish",
    "clam",
    "clams",
    "oyster",
    "oysters",
    "mussel",
    "mussels",
    "scallop",
    "scallops",
    "shellfish",
    "crustacean",
    "crustaceans",
  ]),
  // FISH
  fish: new Set([
    "fish",
    "salmon",
    "tuna",
    "cod",
    "halibut",
    "tilapia",
    "trout",
    "bass",
    "anchovy",
    "anchovies",
    "sardine",
    "sardines",
    "mackerel",
    "haddock",
    "pollock",
    "fish oil",
    "fish sauce",
    "fish extract",
  ]),
  // EGGS
  eggs: new Set([
    "egg",
    "eggs",
    "egg white",
    "egg whites",
    "egg yolk",
    "egg yolks",
    "albumin",
    "egg albumin",
    "egg powder",
    "dried egg",
    "egg protein",
    "whole egg",
    "liquid egg",
  ]),
  // SOY
  soy: new Set([
    "soy",
    "soya",
    "soybean",
    "soybeans",
    "soy protein",
    "soy lecithin",
    "soy flour",
    "soy sauce",
    "tofu",
    "tempeh",
    "edamame",
    "soy oil",
    "soybean oil",
    "textured soy protein",
    "tsp",
    "tvp",
    "textured vegetable protein",
  ]),
};

export const CATEGORY_LABELS = {
  sweeteners: {
    name: "Artificial Sweeteners",
    alertName: "artificial sweeteners",
  },
  colors: { name: "Artificial Colors", alertName: "artificial colors" },
  preservatives: { name: "Preservatives", alertName: "preservatives" },
  flavorEnhancers: {
    name: "Flavor Enhancers",
    alertName: "flavor enhancers",
  },
  dairy: { name: "Dairy Products", alertName: "dairy products" },
  treeNuts: { name: "Tree Nuts", alertName: "tree nuts" },
  peanuts: { name: "Peanuts", alertName: "peanuts" },
  gluten: { name: "Gluten/Wheat", alertName: "gluten" },
  shellfish: { name: "Shellfish", alertName: "shellfish" },
  fish: { name: "Fish", alertName: "fish" },
  eggs: { name: "Eggs", alertName: "eggs" },
  soy: { name: "Soy", alertName: "soy" },
};

export const ALLERGEN_TO_CATEGORY_MAP = {
  soybeans: "soy",
  soybean: "soy",
  soy: "soy",
  soya: "soy",
  milk: "dairy",
  dairy: "dairy",
  eggs: "eggs",
  egg: "eggs",
  peanuts: "peanuts",
  peanut: "peanuts",
  "tree-nuts": "treeNuts",
  nuts: "treeNuts",
  wheat: "gluten",
  gluten: "gluten",
  fish: "fish",
  shellfish: "shellfish",
  crustaceans: "shellfish",
  molluscs: "shellfish",
  mustard: "mustard",
  celery: "celery",
  sesame: "sesame",
  "sesame-seeds": "sesame",
  lupin: "lupin",
  "sulphur-dioxide-and-sulphites": "sulphites",
  sulfites: "sulphites",
};

export const ALERT_CATEGORY_MAPPING = {
  "dairy products": "dairy",
  dairy: "dairy",
  "tree nuts": "treeNuts",
  peanuts: "peanuts",
  peanut: "peanuts",
  gluten: "gluten",
  "gluten/wheat": "gluten",
  shellfish: "shellfish",
  fish: "fish",
  eggs: "eggs",
  egg: "eggs",
  soy: "soy",
  corn: "corn",
  "artificial colors": "colors",
  "artificial color": "colors",
  preservatives: "preservatives",
  preservative: "preservatives",
  "flavor enhancers": "flavorEnhancers",
  "flavor enhancer": "flavorEnhancers",
  "artificial sweeteners": "sweeteners",
  "artificial sweetener": "sweeteners",
};
