// Lifestyle diet presets for common dietary lifestyles
// Each profile maps to specific ingredient alerts that users following these diets would want flagged

export const LIFESTYLE_DIETS = [
  {
    key: "vegan",
    name: "Vegan",
    icon: "🌱",
    color: "#16A34A",
    backgroundColor: "#F0FDF4",
    description: "No animal products",
    disclaimer:
      "This is a general guide — some ingredients like sugar or natural flavors may have animal-derived processing methods not always listed on labels.",
    ingredients: [
      "Gelatin (Animal)",
      "Casein",
      "Whey",
      "Lactose",
      "Honey",
      "Beeswax",
      "Carmine",
      "Shellac",
      "Isinglass",
      "Lard",
      "Tallow",
      "Animal Rennet",
      "Pepsin",
      "L-Cysteine",
      "Glycerin (Animal)",
      "Stearic Acid (Animal)",
      "Mono & Diglycerides",
      "Animal Shortening",
      "Albumin",
      "Lanolin",
    ],
  },
  {
    key: "vegetarian",
    name: "Vegetarian",
    icon: "🥬",
    color: "#059669",
    backgroundColor: "#ECFDF5",
    description: "No meat, fish, or slaughter by-products",
    disclaimer:
      "This covers ingredients derived from slaughtered animals. Dairy and eggs are generally considered vegetarian.",
    ingredients: [
      "Gelatin (Animal)",
      "Lard",
      "Tallow",
      "Animal Rennet",
      "Isinglass",
      "Pepsin",
      "L-Cysteine",
      "Carmine",
      "Shellac",
      "Animal Shortening",
      "Glycerin (Animal)",
      "Stearic Acid (Animal)",
    ],
  },
  {
    key: "keto",
    name: "Keto",
    icon: "🥑",
    color: "#7C3AED",
    backgroundColor: "#F5F3FF",
    description: "Very low carb, high fat",
    disclaimer:
      "Keto limits net carbs to ~20–50g/day. This flags common high-carb ingredients, but always check total carb counts on the nutrition label.",
    ingredients: [
      "Sugar",
      "High Fructose Corn Syrup",
      "Corn Syrup",
      "Dextrose",
      "Maltodextrin",
      "Rice Flour",
      "Wheat Flour",
      "Corn Starch",
      "Potato Starch",
      "Tapioca Starch",
      "Agave",
      "Molasses",
      "Cane Sugar",
      "Brown Rice Syrup",
    ],
  },
  {
    key: "paleo",
    name: "Paleo",
    icon: "🍖",
    color: "#B45309",
    backgroundColor: "#FFFBEB",
    description: "Whole foods, no grains or processed ingredients",
    disclaimer:
      "Paleo focuses on whole, unprocessed foods. This flags common non-paleo additives and ingredients.",
    ingredients: [
      "Soy Lecithin",
      "Soy Protein",
      "Wheat Flour",
      "Wheat Gluten",
      "Corn Syrup",
      "High Fructose Corn Syrup",
      "Canola Oil",
      "Vegetable Oil",
      "Peanut Oil",
      "Maltodextrin",
      "Dextrose",
      "Carrageenan",
      "Xanthan Gum",
      "Sodium Nitrite",
      "Potassium Sorbate",
      "Sodium Benzoate",
    ],
  },
  {
    key: "dairy-free",
    name: "Dairy-Free",
    icon: "🥛",
    color: "#0891B2",
    backgroundColor: "#ECFEFF",
    description: "No milk or milk-derived ingredients",
    disclaimer:
      "Some ingredients like 'natural flavors' may contain trace dairy. Look for certified dairy-free labels for strict avoidance.",
    ingredients: [
      "Casein",
      "Whey",
      "Lactose",
      "Milk Powder",
      "Butter",
      "Cream",
      "Cheese",
      "Buttermilk",
      "Ghee",
      "Curds",
      "Lactalbumin",
      "Lactoferrin",
      "Animal Rennet",
    ],
  },
  {
    key: "gluten-free",
    name: "Gluten-Free",
    icon: "🌾",
    color: "#DC2626",
    backgroundColor: "#FEF2F2",
    description: "No wheat, barley, rye, or related grains",
    disclaimer:
      "Cross-contamination is common. For celiac disease, look for certified gluten-free products. This flags common gluten-containing ingredients.",
    ingredients: [
      "Wheat Flour",
      "Wheat Gluten",
      "Wheat Starch",
      "Barley",
      "Rye",
      "Malt",
      "Malt Extract",
      "Malt Vinegar",
      "Brewer's Yeast",
      "Spelt",
      "Triticale",
      "Semolina",
      "Durum",
      "Farina",
      "Couscous",
    ],
  },
  {
    key: "low-fodmap",
    name: "Low FODMAP",
    icon: "🫃",
    color: "#6D28D9",
    backgroundColor: "#FAF5FF",
    description: "Limits fermentable carbs (for IBS/digestive issues)",
    disclaimer:
      "FODMAP sensitivity varies by person. This flags common high-FODMAP additives found in packaged foods. Work with a dietitian for a personalized plan.",
    ingredients: [
      "High Fructose Corn Syrup",
      "Agave",
      "Honey",
      "Sorbitol",
      "Mannitol",
      "Xylitol",
      "Maltitol",
      "Inulin",
      "Chicory Root Fiber",
      "Fructooligosaccharides",
      "Lactose",
      "Milk Powder",
      "Whey",
      "Apple Juice Concentrate",
      "Onion Powder",
      "Garlic Powder",
    ],
  },
];

// Get a lifestyle diet by key
export function getLifestyleDietByKey(key) {
  return LIFESTYLE_DIETS.find((d) => d.key === key) || null;
}

// Get ingredients that still need to be added (not already in alerts)
export function getNewLifestyleDietIngredients(diet, existingAlerts) {
  const existingNames = new Set(
    existingAlerts.map((a) => a.ingredient_name.toLowerCase().trim()),
  );
  return diet.ingredients.filter(
    (name) => !existingNames.has(name.toLowerCase().trim()),
  );
}
